baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: http://www.codingthoughts.today # Change to your own domain name
permalink: /blog/:title.html
exclude: ["README.md", "CHANGELOG.md", "Gemfile", "Gemfile.lock"]

title: "Chunmeng's Blog"
description: "Personal blog of Chunmeng &middot; Coder & Engineer"

#User Information
author: "Zhang Chunmeng" #Author name
email: "cmzhang7@hotmail.com" #Add Email
github: "https://github.com/silverneo"  #Add your github url here.
stackoverflow: "" #Add your stackoverflow url here.
twitter: "https://twitter.com/cmzhang1991"  #Add your twitter url here.
feedburner: "http://feeds.feedburner.com/ChunmengsBlog" #Add Feeds

show_post_navs: false

paginate: 5 #articles per page
paginate_path: /blog/page:num #makes pagination working

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
comments:
    disqus:
        shortname: "codingthoughts"

analytics:
    google:
        tracking_id: "UA-53702907-1"
